### ISSUE TITLE
[Question] Potential Bug: GetItemAsStringAsync behavior in V4

### ISSUE THREAD

**Issue by francescocristallo** [Blazored/LocalStorage#136]
I updated to V4 and my application's identity system broke.

I was using GetItemAsStringAsync method to retrieve values in V3 (tokens in my case) into my Blazor WebAssembly application.
I found that GetItemAsStringAsync returns the string value with double quotes around it.

Going back to V3 solved the issue.
Using GetItemAsync<string> as per documentation, solved the problem for V4.

Example V4:

```
@page "/"
@inject Blazored.LocalStorage.ILocalStorageService localStorage

<h1>Hello, world!</h1>

<p>
    GetItemAsync string: @Name
</p>
<p>
    GetItemAsStringAsync: @NameAsString
</p>

@code
{
    public string Name { get; set; }
    public string NameAsString { get; set; }

    protected override async Task OnInitializedAsync()
    {
        await localStorage.SetItemAsync("name", "John Smith");
        Name = await localStorage.GetItemAsync<string>("name");
        NameAsString = await localStorage.GetItemAsStringAsync("name");
    }

}
```

![image](https://user-images.githubusercontent.com/9793825/117582338-2b844000-b0c7-11eb-85d6-8d9cdf05b81d.png)

The previous example in V3 returns John Smith without the double quotes in both cases.

I'm not sure if this is a bug for V4 or the expected behavior for the method, I thought it was useful to report it.

**Comment by chrissainty** [comment]
Hi @francescocristallo, thanks for raising this. With v4 this is now the expected behaviour. 

In v3 string values were persisted without serialising them. However, this led to a bug with null values not being retrieved correctly. Now all values are serialised before storing them, hence the extra quotes you're now seeing. 

As you've found, using GetItemAsync is the preferred option for retrieving values now.
