### ISSUE TITLE
[Question] Issues Deserializing items from Local Storage.

### ISSUE THREAD

**Issue by Christian-Oleson** [Blazored/LocalStorage#155]
First off, thank you all for this lib!

100% this is most likely me missing something obvious, but... I'm having some issues with saving and retrieving complex objects from Local Storage. I serialize the Objects to a JSON string, and then I save them to local storage. I can see them in local storage, but I cannot deserialize them. If I use the default implementation of await `LocalStorageService.SetItemAsync(key, jsonValue);`
I see a lot of unicode escaping of chars:
\u0022 instead of "
This would see fine, normally, but for some reason something I have configured is tripping over this, because if I call:
```
await LocalStorageService.SetItemAsync(key, jsonValue);
await LocalStorageService.GetItemAsync<T>(key);
```
My serializer immediately fails to read the JSON. If instead I use the JS Runtime:
`await JsRuntime.InvokeVoidAsync("localStorage.setItem", key, jsonValue);`
and then I use the LocalStorageService to get the item:
`await LocalStorageService.GetItemAsync<T>(key);`
It succeeds. The only difference is the unicode value. So, my questions are:
1. Is there a way to stop this behavior?
2. Do you all have an example of a working application using System.Text.Json and Blazored.LocalStorage where we are saving complex objects to the local storage and retrieving them with success? This is not questioning whether this library is working, just is a way for me to see what I clearly must be doing wrong.

**Comment by chrissainty** [comment]
Hi @Christian-Oleson, I think the problem here is double serialisation. The library serialises the data for you by default. If you're serialising it yourself first and then passing it to `SetItemAsync`, it will be serialised again.

So you have two options, let the library handle the serialisation for you, or continue to manage it yourself. If you want to manage it yourself you should use the `SetItemAsStringAsync()` and `GetItemAsStringAsync()` methods as they don't perform any serialisation. 

It's also worth pointing out that the library is very configurable. If you have specific requirements around JSON serialisation, for example you need to use NewtonsoftJson (we use System.Text.Json by default), you can provide an implementation for the IJsonSerializer interface (checkout the readme and sample projects for more info on that).

**Comment by Christian-Oleson** [comment]
> Hi @Christian-Oleson, I think the problem here is double serialisation. The library serialises the data for you by default. If you're serialising it yourself first and then passing it to `SetItemAsync`, it will be serialised again.
> 
> So you have two options, let the library handle the serialisation for you, or continue to manage it yourself. If you want to manage it yourself you should use the `SetItemAsStringAsync()` and `GetItemAsStringAsync()` methods as they don't perform any serialisation.
> 
> It's also worth pointing out that the library is very configurable. If you have specific requirements around JSON serialisation, for example you need to use NewtonsoftJson (we use System.Text.Json by default), you can provide an implementation for the IJsonSerializer interface (checkout the readme and sample projects for more info on that).

Hey Chris,

Thanks for the response. It looks like you were right. I wasn't thinking the method was serializing the data out of the box, so I was serializing this first and then passing my JSON to the method. I stopped doing so and now am able to work correctly with my local storage. Thanks again!
