### ISSUE TITLE
[Bug] Impossible to make it work

### ISSUE THREAD

**Issue by iso8859** [Blazored/LocalStorage#221]
I did test LocalStorage nuget for a WebAssembly and it worked great.
Impossible to make it work in a very small game project.

I tried everything during 2 hours, once I got a value in local storage. It was the first and last time it worked, I don't know why.
No exception, no console message, nothing. I also tried to serialize myself to avoid exception here.

The projet is open source and very simple, so you can reproduce it easily.
https://github.com/iso8859/cousinzins2023

Hope it helps to make this package more reliable.

**Comment by chrissainty** [comment]
Hi @iso8859,

There are some bug in your code, but the one causing the issue is here:

https://github.com/iso8859/cousinzins2023/blob/9ae312648589c2972fdb82d3ce7ee8bc793f2057/Pages/Index.razor#L23C9-L23C62

It should be written like this:

```csharp
<button @onclick="reset">Tout effacer</button>
```

I'm not sure why, but the way you've written is causing the `reset` method to be called after every `onchange` event is handled. This effectively deletes whatever you've just written into local storage.
