### ISSUE TITLE
blazored-localstorage.js

### ISSUE THREAD

**Issue by Scotty-Hudson** [Blazored/LocalStorage#30]
With the preview 8 update, adding <script src="_content/Blazored.LocalStorage/blazored-localstorage.js"></script> did not work. The browser reports this file cannot be found. As a workaround, I manually added blazored-localstorage.js to my client project and changed the script tag in index.html to point to that.

**Comment by Scotty-Hudson** [comment]
It should have looked at the pull request #29 before reporting this. It looks like this pull request will take care of this issue.

**Comment by chrissainty** [comment]
@Scotty-Hudson I've had this report now several times. Are you experiencing this issue when developing or after publishing? If it's during development then make sure your on the latest version of the package and then run a clean and re-build and also clear your browser cache and then JS files should show up as expected. 

If you're seeing this issue after publishing then this is an issue with the new Razor Class Library and should be fixed in Preview 9

**Comment by chrissainty** [comment]
I've just pushed a new version of the package which no longer needs a JavaScript file. Hopefully, this should remove the issue entirely.

**Comment by Scotty-Hudson** [comment]
@chrissainty It was when developing. I never tried after publishing with the previous version. With the version you just push I removed the script reference to the JavaScript file in index.html. It now works beautifully. Thank you addressing this and sharing your work. I really appreciate it.
