### ISSUE TITLE
synchronous operation with server-side not work

### ISSUE THREAD

**Issue by julienGrd** [Blazored/LocalStorage#36]
Hi, and thanks for your work !

I try to use your library in a server-side project with synchronous call, but when i call the GetItem (in onAfterRender method), I have this following error :
IJSInProcessRuntime not available

How to reproduce :
- update your server side demo and replace the storageService by a ISyncLocalStorageService, and make all method and call synchronous. Launch the project => bug "IJSInProcessRuntime not available"

thanks for your help !

Julien

**Comment by Sharaf-Mansour** [comment]
I have the same issue here too with Server-Side Application Error: ```System.InvalidOperationException: 'IJSInProcessRuntime not available'```
![image](https://user-images.githubusercontent.com/55330747/64913047-152eb100-d739-11e9-9dd6-cf4f676f0b86.png)
@chrissainty Thank you for your Awesome Work and Great Help!

**Comment by chrissainty** [comment]
@julienGrd @Sharaf-Mansour Apologies for my late reply, I've been away for the past week. 

The synchronous APIs are only available in Blazor WebAssembly apps not in Blazor Server apps, hence your issues. This is because the JS Interop happens over the SignalR connection and must be awaited. 

I did have this as a note in the Readme, but it seems to have been lost. I've now updated it to show the warning again.
