### ISSUE TITLE
[Feature Request] Implement IEnumerable or an alternative way to list keys

### ISSUE THREAD

**Issue by titanix** [Blazored/LocalStorage#80]
Hi, I face a problem using the library. Would it be possible to implement the feature presented   below?

**Is your feature request related to a problem? Please describe.**
The interface ILocalStorageService does not provide any way to lists the key contained in local storage. In Javascript [the solution](https://stackoverflow.com/questions/5410745/how-can-i-get-a-list-of-the-items-stored-in-html-5-local-storage-from-javascript) is to iterate on the localStorage object.

This is however not implemented here and not alternative way is provided. Consequently, it's necessary to manually use the local storage to bookkeep the list of key, which is somewhat cumbersome.

**Describe the solution you'd like**
Implementation of the relevant interfaces (IEnumerable, IEnumerator) would allow consumers to use the same pattern as in Javascript to list keys present in local storage.

**Describe alternatives you've considered**
I've considered manually use the local storage to bookkeep the list of key.

**Additional context**
Keys are generated dynamically based on current time.

**Comment by chrissainty** [comment]
Hi @titanix, I think this would be a good feature to add. Would you be interested in raising a PR?

**Comment by jan-johansson-mr** [comment]
Maybe I can chip in on this? It seems like a nice feature, but I can wait until I know if @titanix would prefer to raise a PR.

**Comment by titanix** [comment]
Sorry for late reply.

First I noticed that the API exposes Length and Key(int) which combined can solve my issue. This is what I did in my project.

Second, I actually tried implementing the IEnumerator anyway, and while the library build somehow the changes aren't taken in account in the sample project on my main machine (VS Code/macOS). This is purely an issue on my machine, yet that's a blocker since I wanted to update sample and documentation too.

Third, as the library has both synchronous and asynchronous APIs, implementing IEnumerator would likely means implementing IAsyncEnumerable as well, withfor which I had 0 experience...

So yes, @jan-johansson-mr you could do ta PR if you want. 
My code was almost just the portion below, placed i LocalStorageService.cs (+ : IEnumerable here and there). It needs to handle underlying collection changes too, which this code doesn't.

```csharp
class KeyEnumerator : IEnumerator
{
    LocalStorageService _localStorageService;
    int _current;

    internal KeyEnumerator(LocalStorageService localStorageService)
    {
        _localStorageService = localStorageService;
    }

    public object Current => _localStorageService.Key(_current);

    public bool MoveNext()
    {
        if(_current == _localStorageService.Length() - 1)
        {
            return false;
        }

        return true;
    }

    public void Reset()
    {
        _current = 0;
    }
}

public IEnumerator GetEnumerator()
{
    return new KeyEnumerator(this);
}
```

**Comment by jan-johansson-mr** [comment]
Thanks @titanix, I can have a go with it, and see what happens :-)

**Comment by jan-johansson-mr** [comment]
Hi,

Upon reviewing the feature request, we have a design decision to make. The solution is targeting C# 7.3 (via standard 2.0), but to introduce the nice `IAsyncEnumerable` pattern we need to target C# 8.0 (via standard 2.1).

I don't want to break things all by myself so please give me your feedback on the following suggestions

- We go with standard 2.0 and use the design proposed by @titanix (kind of an `IAsyncEnumerable`, or SQL like cursor)
- Or we go with standard 2.0 and take a snapshot of keys before starting returning keys by `IEnumerable` (can have a performance impact if we have a bigger storage, but I doubt anyone will notice that much, but again, maybe someone will)
- Or we go with standard 2.1 and can enumerate key by key in a lazy manner by `IAsyncEnumerable` without impact on performance regardless of storage size (with the bonus of very slim code)

Is there a reason to remain with net standard 2.0? Is there a need to be .net framework compatible (maybe on the server side if someone want to create a server blazor on framework instead of core)?

Thanks,
@chrissainty, @titanix

**Comment by chrissainty** [comment]
@jan-johansson-mr I can't see any reason not to move to .NET Standard 2.1. This package can only be used in Blazor apps and both hosting models, Blazor WebAssembly and Blazor Server, support net standard 2.1.

**Comment by titanix** [comment]
> (can have a performance impact if we have a bigger storage, but I doubt anyone will notice that much, but again, maybe someone will)

One thing to consider, because implementing IAsyncEnumerable would require more work, is that the underlying `localStorage` API in Javascript is actually synchronous (or so the web tells). So, even if some async feature is implemented in C#, I'd bet this wouldn't really improve perfs anyway.

**Comment by jan-johansson-mr** [comment]
Thanks gentlemen,
I'll be targeting 2.1 then :-)

**Comment by chrissainty** [comment]
Based upon the further discussion on #84, we're not going to be adding this feature.
